name: Will Troiani
markdown: kramdown
remote_theme: pages-themes/midnight

defaults: 
  - 
    scope: 
      path: "" 
      type: "posts" 
    values: 
      layout: "post"
  -
    scope:
      path: ""
      type: "pages" 
    values:
      layout: "page"
